project:
  - name: project_name
    types: String,Boolean
    example: |
      config.lookbook.project_name = "Lookbook Demo" # custom project name
      config.lookbook.project_name = false # hide the project name
    description: |
      Customise or disable the project name displayed in the Lookbook header. Defaults to the parent application's name.

  - name: project_logo
    types: String,Boolean
    example: |
      config.lookbook.project_logo = "<svg>...</svg>" # custom SVG logo
      config.lookbook.project_logo = false # hide the logo
    description: |
      Customise or disable the logo displayed in the Lookbook header.

previews:
  - name: preview_collection_label
    types: String
    default: "Previews"
    example: config.lookbook.preview_collection_label = "Component Previews"
    description: The label used to denote the previews section of the sidebar nav.

  - name: preview_paths
    types: Array
    default: "[]"
    example: config.lookbook.preview_paths = ["path/to/my/previews"]
    description: Array of additional directory paths that Lookbook should look for previews in.

  - name: preview_display_options
    types: Hash
    default: "{}"
    example: |
      config.lookbook.preview_display_options = {
        bg_color: "#fff",
        max_width: "100%"
      }
    description: Default (fallback) display params that will be merged with any preview-specific display params and made available in the preview layout template.

  - name: preview_controller
    types: String
    default: '"Lookbook::PreviewController"'
    example: config.lookbook.preview_controller = "MyCustomController"
    description: The controller used when rendering previews.

  - name: preview_inspector.drawer_panels
    types: Array
    default: '[:source, :notes, :params, "*"]'
    example: config.lookbook.preview_inspector.drawer_panels = [:notes, :params]
    description: List of panels to display in the preview inspector

  - name: preview_inspector.sidebar_panels
    types: Array
    default: '[:previews, :pages]'
    example: config.lookbook.preview_inspector.sidebar_panels = [:pages, :previews]
    description: Controls the order and availability of the sidebar navigation panels.

  - name: preview_embeds.enabled
    types: Boolean
    default: "true"
    example: config.lookbook.preview_embeds.enabled = false
    description: Whether or not preview embeds are enabled.

  - name: preview_embeds.policy
    types: String
    default: '"SAMEORIGIN"'
    example: config.lookbook.preview_embeds.policy = "ALLOWALL"
    description: |
      Preview embeds security policy.
      `ALLOWALL` - allow on any site.
      `SAMEORIGIN` - only allow on same domain
      `DENY` - don't allow embedding at all

  - name: preview_embeds.panels
    types: Array
    default: "[]"
    example: config.lookbook.preview_embeds.panels = [:notes, :source]
    description: List of panels to display in embeds by default

  - name: preview_embeds.actions
    types: Array
    default: "[]"
    example: config.lookbook.preview_embeds.actions = [:open]
    description: List of actions to include in embeds by default

  - name: preview_disable_action_view_annotations
    types: Boolean
    default: "true"
    example: config.lookbook.preview_disable_action_view_annotations = false
    description: Turns off action view filename annotations when generating rendered component source.

  - name: preview_sort_scenarios
    types: Boolean
    default: "false"
    example: "config.lookbook.preview_sort_scenarios = true"
    description: |
      Whether or not to sort preview examples in the navigation alphabetically
      (as opposed to displaying them in the order they are defined in the preview class).

pages:
  - name: page_collection_label
    types: String
    default: "Pages"
    example: config.lookbook.page_collection_label = "Docs"
    description: The label used to denote the pages section of the sidebar nav.

  - name: page_paths
    default: "[]"
    types: Array
    example: config.lookbook.page_paths = ["path/to/my/pages"]
    description: Array of additional directory paths that Lookbook should look for pages in.

  - name: page_route
    types: String
    default: '"pages"'
    example: config.lookbook.page_route = "docs"
    description: The URL segment used to prefix page routes.

  - name: page_options
    types: Hash
    default: "{}"
    example: |
      config.lookbook.page_options = {
        footer: false,
        data: {
          brand_colors: {
            red: "#ff0000"
          }
        }
      }
    description: |
      Frontmatter defaults for pages.
      These will be merged with any page-level frontmatter data. Options set in the frontmatter
      will override those set at the global level (apart from 'data', which will be deep-merged
      with the any globally defined data).

components:
  - name: component_paths
    default: "['app/views']"
    types: Array
    example: config.lookbook.component_paths << "path/to/my/components"
    description: |
      Array of additional directory paths to look for components in.
      _Not applicable for ViewComponent components_

theming:
  - name: ui_theme
    types: String
    default: '"indigo"'
    example: config.lookbook.ui_theme = "zinc"
    description: |
      The UI theme to use. Available options are: `indigo`, `blue`, `zinc`, `green`, `rose`.

  - name: ui_theme_overrides
    types: Hash
    default: "{}"
    example: |
      config.lookbook.ui_theme_overrides = {
        header: "hotpink"
      }
    description: For overriding theme CSS variables with custom values.

  - name: ui_favicon
    types: Boolean,String
    default: "true"
    example: |
      config.lookbook.ui_favicon = false # no favicon
      config.lookbook.ui_favicon = "<svg>...</svg>" # custom SVG favicon
    description: |
      Customise or disable the favicon served by Lookbook.

markdown:
  - name: markdown_options.tables
    types: Boolean
    default: "true"
    example: config.lookbook.markdown_options.tables = false
    description: Enable/disable support for tables

  - name: markdown_options.fenced_code_blocks
    types: Boolean
    default: "true"
    example: config.lookbook.markdown_options.fenced_code_blocks = false
    description: Enable/disable support for fenced code blocks

  - name: markdown_options.disable_indented_code_blocks
    types: Boolean
    default: "true"
    example: config.lookbook.markdown_options.disable_indented_code_blocks = false
    description: Enable/disable support for indented code blocks

  - name: markdown_options.lax_spacing
    types: Boolean
    default: "true"
    example: config.lookbook.markdown_options.lax_spacing = false
    description: Enable/disable support for lax spacing

highlighter:
  - name: highlighter_options.dark
    types: Boolean
    default: "false"
    example: config.lookbook.highlighter_options.dark = true
    description: Use dark theme variant for highlighted code blocks

debugging:
  - name: log_level
    types: Integer
    default: 2
    example: config.lookbook.log_level = 3
    description: |
      The minimum level to use for displaying log messages.
      _Only applicable if no logger has been set in the parent application_, otherwise Lookbook
      will use that logger and the log level value that has been set on it.

  - name: log_use_rails_logger
    group: debugging
    types: Boolean
    default: "true"
    example: config.lookbook.log_use_rails_logger = true
    description: Whether or not Lookbook should use the Rails logger when it is present.

  - name: debug_menu
    group: debugging
    types: Boolean
    default: "Rails.env.development?"
    example: "config.lookbook.debug_menu = false # always hide the debug menu"
    description: Whether or not to show the debug menu in the Lookbook header.

system:
  - name: reload_on_change
    types: Boolean
    default: "!config.cache_classes && config.reload_classes_only_on_change"
    example: config.lookbook.reload_on_change = true
    description: |
      By default Lookbook uses the value of the `cache_classes` and `reload_classes_only_on_change` Rails config options to decide if
      it should attempt to update the preview data after changes. If set the value of this config option will take precedence and be used instead.

  - name: live_updates
    types: Boolean
    default: "true"
    example: config.lookbook.live_updates = false
    description: |
      Apps that include the `listen` and `actioncable` gems will automatically have live UI updates enabled (in development).
      Setting `live_updates` to `false` will prevent this behaviour and ensure no websocket connections are created.
      This is automatically handled in production.

  - name: listen_paths
    types: Array
    default: "[]"
    example: config.lookbook.listen_paths = ["directory/to/watch"]
    description: |
      Specify additional directories to listen for changes in.
      Component, preview and pages directories are always watched.

  - name: listen_extensions
    group: system
    types: Array
    default: "[]"
    example: config.lookbook.listen_extensions = ["js", "css"]
    description: |
      Specify additional extensions for file types that should be watched for changes.
      Files with **.rb** and **.html.*** extensions are always watched.
